#!/usr/bin/env python3
"""Deterministic, idempotent generator for the Oraclous Knowledge Base index.

Walks the canonical content sections, reads each section's ``index.md``
frontmatter ``title`` and first prose paragraph (one-line summary), counts the
``.md`` files in the section, and (re)generates two files at the repository
root: ``index.md`` (navigable root index) and ``llms.txt`` (llms.txt-convention
entry point for agents).

Standard library only. No PyYAML — the ``title:`` frontmatter line is parsed
with a regex.

Usage:
    python3 scripts/build_kb_index.py            # write index.md + llms.txt
    python3 scripts/build_kb_index.py --check    # CI/pre-commit: verify only

In ``--check`` mode the generator builds the output in memory and exits 1 with
a diff hint if the on-disk files differ from what would be generated; it exits 0
when they are already current.

Output is reproducible: sections are processed in alphabetical order by path,
and generated files carry a "GENERATED — do not edit by hand" header.
"""

import argparse
import difflib
import os
import re
import sys

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Repo root is the parent of the directory containing this script.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_NAME = "Oraclous Knowledge Base"
PROJECT_TAGLINE = (
    "The canonical knowledge base for the Oraclous platform — architecture, "
    "decisions, engineering practice, operations, and compliance."
)

# The eleven canonical content sections. Everything else at the root
# (_mirror/, scripts/, .githooks/, .claude/, .git/) is non-content and skipped.
CONTENT_SECTIONS = [
    "adr",
    "architecture",
    "compliance",
    "contracts",
    "engineering",
    "flows",
    "frontend",
    "meta",
    "operations",
    "releases",
    "services-reference",
]

# Directories never treated as content sections, for defence in depth.
SKIP_DIRS = {"_mirror", ".git", "scripts", ".githooks", ".claude"}

GENERATED_MARKER_MD = (
    "<!-- GENERATED by scripts/build_kb_index.py — do not edit by hand; "
    "run the script. -->"
)
GENERATED_MARKER_TXT = (
    "<!-- GENERATED by scripts/build_kb_index.py — do not edit by hand; "
    "run the script. -->"
)

# Curated key entry points: the most important canonical docs, by relative path.
# Only those that actually exist on disk are emitted.
KEY_ENTRY_POINTS = [
    (
        "architecture/index.md",
        "Platform Architecture",
        "The architectural source of truth implementation conforms to.",
    ),
    (
        "engineering/index.md",
        "Engineering governance",
        "Test strategy, git workflow, PR conventions, Definition of Done — the "
        "engineering operating contract.",
    ),
    (
        "releases/index.md",
        "Releases",
        "Per-release execution contracts; the input to ticket creation.",
    ),
    (
        "adr/index.md",
        "ADR registry",
        "Every Architecture Decision Record, newest superseding older.",
    ),
    (
        "services-reference/index.md",
        "Services Reference",
        "One reference page per target service.",
    ),
]

TITLE_RE = re.compile(r'^\s*title:\s*(.+?)\s*$')


# ---------------------------------------------------------------------------
# Parsing helpers
# ---------------------------------------------------------------------------

def _strip_quotes(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        return value[1:-1]
    return value


def split_frontmatter(text):
    """Return (frontmatter_lines, body_lines).

    Frontmatter is a leading ``---`` ... ``---`` block. If absent, the whole
    document is body and frontmatter is empty.
    """
    lines = text.splitlines()
    if lines and lines[0].strip() == "---":
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                return lines[1:i], lines[i + 1:]
    return [], lines


def parse_title(frontmatter_lines, fallback):
    """Extract ``title`` from frontmatter lines via regex, else return fallback."""
    for line in frontmatter_lines:
        m = TITLE_RE.match(line)
        if m:
            return _strip_quotes(m.group(1))
    return fallback


def _is_prose(line):
    """True when a line is real summary prose, not heading/metadata/markup."""
    stripped = line.strip()
    if not stripped:
        return False
    if stripped.startswith("#"):           # markdown heading
        return False
    if stripped.startswith(("|", ">", "<")):  # table / blockquote / html block
        return False
    if stripped.startswith(("- ", "* ", "+ ")):  # list item
        return False
    if re.match(r'^\d+\.\s', stripped):    # ordered list item
        return False
    # Document-status / maintained-by metadata lines (e.g. "**Document status:** ...").
    if re.match(r'^\*\*[^*]+:\*\*', stripped):
        return False
    return True


def _normalise_summary(paragraph):
    """Collapse whitespace and strip markdown link syntax to plain text."""
    text = " ".join(paragraph.split())
    # [label](target) -> label
    text = re.sub(r'\[([^\]]+)\]\([^)]*\)', r'\1', text)
    # **bold** / *italic* / `code` markers -> inner text
    text = re.sub(r'\*\*([^*]+)\*\*', r'\1', text)
    text = re.sub(r'\*([^*]+)\*', r'\1', text)
    text = re.sub(r'`([^`]+)`', r'\1', text)
    return text.strip()


def first_summary(body_lines, fallback):
    """First non-empty prose paragraph as a normalised one-liner, else fallback."""
    paragraph = []
    for line in body_lines:
        if _is_prose(line):
            paragraph.append(line)
        elif paragraph:
            break
        # else: still searching for the start of prose
    if not paragraph:
        return fallback, True  # (summary, missing_flag)
    return _normalise_summary(" ".join(paragraph)), False


def derive_title_from_section(section):
    return section.replace("-", " ").replace("_", " ").title()


# ---------------------------------------------------------------------------
# Section scanning
# ---------------------------------------------------------------------------

class SectionInfo:
    def __init__(self, section, title, summary, file_count, missing):
        self.section = section
        self.title = title
        self.summary = summary
        self.file_count = file_count
        self.missing = missing  # list of human-readable problems

    @property
    def index_rel(self):
        return "%s/index.md" % self.section


def count_md_files(section_dir):
    total = 0
    for _root, dirs, files in os.walk(section_dir):
        # prune skip dirs anywhere in the tree
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        total += sum(1 for f in files if f.endswith(".md"))
    return total


def scan_section(section):
    section_dir = os.path.join(REPO_ROOT, section)
    index_path = os.path.join(section_dir, "index.md")
    problems = []
    fallback_title = derive_title_from_section(section)
    fallback_summary = "(no summary available)"

    if not os.path.isfile(index_path):
        problems.append("missing index.md")
        return SectionInfo(section, fallback_title, fallback_summary, 0, problems)

    with open(index_path, "r", encoding="utf-8") as fh:
        text = fh.read()

    frontmatter, body = split_frontmatter(text)
    title = parse_title(frontmatter, fallback_title)
    if title == fallback_title:
        problems.append("no parseable frontmatter title (derived from path)")

    summary, summary_missing = first_summary(body, fallback_summary)
    if summary_missing:
        problems.append("no parseable prose summary")

    file_count = count_md_files(section_dir)
    return SectionInfo(section, title, summary, file_count, problems)


def scan_all():
    return [scan_section(s) for s in sorted(CONTENT_SECTIONS)]


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def render_index_md(sections):
    out = []
    out.append(GENERATED_MARKER_MD)
    out.append("")
    out.append("# %s" % PROJECT_NAME)
    out.append("")
    out.append(PROJECT_TAGLINE)
    out.append("")
    out.append("## How agents should use this")
    out.append("")
    out.append(
        "This index is the token-efficiency contract for the knowledge base. "
        "The KB is large (~100+ markdown files); reading the whole tree wastes "
        "the context budget. Instead:"
    )
    out.append("")
    out.append("1. Consult **this index** (or root `llms.txt`) to choose a section.")
    out.append("2. Open the **ONE** relevant `<section>/index.md`.")
    out.append("3. Open **only** the specific file(s) you need from that section.")
    out.append("")
    out.append(
        "Never read the whole tree or open many files speculatively. "
        "`oraclous-knowledge` is the canonical KB; Confluence is a read-only mirror."
    )
    out.append("")
    out.append("## Sections")
    out.append("")
    out.append("| Section | Summary | Files |")
    out.append("| --- | --- | --- |")
    for s in sections:
        link = "[%s](%s)" % (s.title, s.index_rel)
        out.append("| %s | %s | %d |" % (link, s.summary, s.file_count))
    out.append("")
    out.append("## Non-canonical")
    out.append("")
    out.append(
        "`_mirror/` is a read-only dump of the Confluence mirror and is **not "
        "canonical**. Do not cite it as source of truth; use the sections above."
    )
    out.append("")
    return "\n".join(out)


def render_llms_txt(sections):
    out = []
    out.append(GENERATED_MARKER_TXT)
    out.append("")
    out.append("# %s" % PROJECT_NAME)
    out.append("")
    out.append("> %s" % PROJECT_TAGLINE)
    out.append("")
    out.append(
        "This file follows the llms.txt convention, adapted for a repository "
        "(relative links, not URLs). To answer from this knowledge base, read "
        "this file first, then open the single most relevant section index, then "
        "open only the specific file you need — never read the whole tree."
    )
    out.append("")
    out.append("## Knowledge base sections")
    out.append("")
    for s in sections:
        out.append("- [%s](%s): %s" % (s.title, s.index_rel, s.summary))
    out.append("")

    # Key entry points — only those that exist on disk.
    entry_lines = []
    for rel, label, summary in KEY_ENTRY_POINTS:
        if os.path.isfile(os.path.join(REPO_ROOT, rel)):
            entry_lines.append("- [%s](%s): %s" % (label, rel, summary))
    if entry_lines:
        out.append("## Key entry points")
        out.append("")
        out.extend(entry_lines)
        out.append("")

    out.append("## Optional")
    out.append("")
    out.append(
        "- `_mirror/`: a read-only Confluence mirror (non-canonical). "
        "Ignore for retrieval; the sections above are the source of truth."
    )
    out.append("")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Write / check
# ---------------------------------------------------------------------------

TARGETS = ("index.md", "llms.txt")


def build_outputs():
    sections = scan_all()
    return {
        "index.md": render_index_md(sections),
        "llms.txt": render_llms_txt(sections),
    }, sections


def read_existing(name):
    path = os.path.join(REPO_ROOT, name)
    if not os.path.isfile(path):
        return None
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def write_outputs(outputs):
    for name in TARGETS:
        path = os.path.join(REPO_ROOT, name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(outputs[name])


def check_outputs(outputs):
    """Return True when on-disk matches generated; print diffs otherwise."""
    clean = True
    for name in TARGETS:
        existing = read_existing(name)
        generated = outputs[name]
        if existing is None:
            clean = False
            print("[build_kb_index] %s is missing — run: python3 "
                  "scripts/build_kb_index.py" % name, file=sys.stderr)
            continue
        if existing != generated:
            clean = False
            print("[build_kb_index] %s is stale — run: python3 "
                  "scripts/build_kb_index.py" % name, file=sys.stderr)
            diff = difflib.unified_diff(
                existing.splitlines(), generated.splitlines(),
                fromfile="%s (on disk)" % name,
                tofile="%s (generated)" % name, lineterm="",
            )
            for line in diff:
                print(line, file=sys.stderr)
    return clean


def report_missing(sections):
    flagged = [s for s in sections if s.missing]
    if flagged:
        print("[build_kb_index] sections needing attention:", file=sys.stderr)
        for s in flagged:
            print("  - %s: %s" % (s.section, "; ".join(s.missing)),
                  file=sys.stderr)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="verify on-disk index.md/llms.txt are current; exit 1 if not",
    )
    args = parser.parse_args(argv)

    outputs, sections = build_outputs()
    report_missing(sections)

    if args.check:
        if check_outputs(outputs):
            print("[build_kb_index] index.md and llms.txt are up to date.")
            return 0
        return 1

    write_outputs(outputs)
    print("[build_kb_index] wrote index.md and llms.txt (%d sections)."
          % len(sections))
    return 0


if __name__ == "__main__":
    sys.exit(main())
